### ISSUE TITLE
Backport contacts backup app to `android10`

### ISSUE THREAD

**Issue by h01ger** [seedvault-app/seedvault#261] opened 2021-05-29 14:49 UTC
first off: seedvault (and its integration into lineage) is pretty neat, kudos!

I've done a backup on a phone running lineage 17.1 (from May 25th) and then a restore on another phone running lineage 18.1 (from today, so May 29th) and while most everything was restored nicely, the contacts were not. sms and phone call history is there, but just with (phone) numbers.

I sadly don't have another device running 17.1 else I would try restore there...

**Comment by grote** [comment] 2021-05-30 17:45
Could be a duplicate of #237.

Did you check if it ever made a backup of local contacts? Did you sync your contacts with a sync adapter to a server or are these stored only locally?

**Comment by h01ger** [comment] 2021-05-31 18:24
I never synced my contacts, I've only stored them on the device.

Also: 

$ adb shell bmgr backupnow org.calyxos.backup.contacts
Running incremental backup for 1 requested packages.
Package org.calyxos.backup.contacts with result: Package not found
Backup finished with result: Success

Happy to do more debugging, if advised how. (I know how to use adb but have only used logcat once and forgot how...)

**Comment by h01ger** [comment] 2021-05-31 18:31
I then ran "adb pull /data/data/com.android.providers.contacts/databases/contacts2.db" and ran that through sqlite3:

sqlite> SELECT * FROM view_data WHERE is_primary = 1;
Error: no such collation sequence: PHONEBOOK

Interestingly when I ran that same command again, I got all my contacts.

SELECT lookup, data1, account_type FROM view_data; 
also showed me my contacts

**Comment by grote** [comment] 2021-05-31 18:43
>  `Package org.calyxos.backup.contacts with result: Package not found`

This would explain why the backup didn't work. 

What is `adb shell pm list packages | grep contacts` giving you?

**Comment by h01ger** [comment] 2021-05-31 19:22
$ adb shell pm list packages | grep contacts
package:com.android.contacts
package:com.android.providers.contacts

(stock lineage 17.1 install with some apps from f-droid)

**Comment by grote** [comment] 2021-05-31 19:25
Yeah so your LineageOS version/build does include Seedvault, but not the app responsible for doing the contact backups.

Maybe @mikeNG knows why that could be. If not, open a bug with them.

**Comment by h01ger** [comment] 2021-05-31 19:31
is there a way to install that app manually?

I guess I will find out how to file bugs against LineageOS soon then, though probably only in 48h or so...

Thanks for your help so far!

**Comment by mikeNG** [comment] 2021-05-31 22:50
> Yeah so your LineageOS version/build does include Seedvault, but not the app responsible for doing the contact backups.
> 
> Maybe @mikeNG knows why that could be. If not, open a bug with them.

That's because LineageOS 17.1 is using `android10` branch of seedvault that doesn't have the contacts backup app.

**Comment by h01ger** [comment] 2021-06-01 00:35
is there any problem with adding that app to that branch? :)

**Comment by grote** [comment] 2021-06-01 12:21
I am not a aware of a problem except that we barely have time to maintain the branch for the latest Android version. 

Feel free to backport https://github.com/seedvault-app/seedvault/commit/0272a094ec8bc86286bc108457f852122e2f558e to the android10 branch, test it and open a PR for it. The [`minSdkVersion`](https://github.com/seedvault-app/seedvault/commit/0272a094ec8bc86286bc108457f852122e2f558e#diff-0858af797ccf4f4e112e4e4204c503c8c5e9648dcdd78a1d3b9177e82dfa98caR10) in the contacts backup app would need to be set to `29`.

However, it might be faster to just use the manual backup to `.vcf` feature of the contacts app for your personal use-case.

**Comment by h01ger** [comment] 2021-06-03 13:19
Yeah, for now I'm just exporting .vcf from within the contacts app and then I backup this via my usual backup script / soon syncthing.

Thanks for the pointers how to backport the contacts backup app! however I both lack any android/lineage build knowledge and time. So I also very well understand you lacking the time for maintaining anything else than the latest adroid version.

I hope someone else will pick this up! Thanks again for the quick and helpful feedback!

**Comment by grote** [comment] 2022-08-22 20:58
I am closing the ticket for now. Once somebody will want to do this, we can always re-opne.

**Closed by grote** 2022-08-22 20:58 UTC
Labels: help wanted, good first issue
