### ISSUE TITLE
Message "Waiting to back up..." for local contacts

### ISSUE THREAD

**Issue by aereaux** [seedvault-app/seedvault#237] opened 2021-04-10 01:10 UTC
I am using seedvault on lineageos 18.1.  The "Local contacts" entry is stuck at "Waiting to back up...", even though I have contacts on device (I don't have any sort of cloud syncing enabled for them).  Is there something I need to enable to get this to work?

**Comment by grote** [comment] 2021-04-12 18:29
It should work automatically. Is there a Local Contacts Backup app installed?

Do you know how to run adb commands?

If so, try `adb shell bmgr backupnow org.calyxos.backup.contacts`

**Comment by aereaux** [comment] 2021-04-12 18:35
Yeah, there appears to be a Local Contacts Backup app.  The adb command gives me this:
```
Running incremental backup for 1 requested packages.
Package @pm@ with result: Success
Package org.calyxos.backup.contacts with result: Transport rejected package because it wasn't able to process it at the time
Backup finished with result: Success
```

**Comment by grote** [comment] 2021-04-12 18:36
Interesting, can you also provide the logcat from running this command?

**Comment by aereaux** [comment] 2021-04-12 18:42
Yeah, looking at it now, it's pretty long.  Maybe this is relevant?
```
04-12 11:39:52.470  1759  1778 I ContactsBackupAgent: onFullBackup - found no contacts. Not backing up.
```

**Comment by grote** [comment] 2021-04-12 18:45
OK, so the app isn't finding any contacts matching its criteria. Sure they are not associated with any sort of account, but show as "on device"?

**Comment by aereaux** [comment] 2021-04-12 18:46
Yeah, when I edit a contact it says "Saving to Device".

**Comment by grote** [comment] 2021-04-12 18:53
I am afraid the only way to debug this further is to install a test app with a modified query and look at its result to find out why it is not matching in your case.

If you have root, one could also extract the contacts sqlite database from the device and have a look there.

**Comment by aereaux** [comment] 2021-04-12 18:54
I have adb root.  What would I need to look for in the contacts db?  Or I might be able to install such a test app.

**Comment by grote** [comment] 2021-04-12 19:04
With adb root: `adb pull /data/data/com.android.providers.contacts/databases/contacts2.db`

If you open this file with `sqlitebrowser` (or a similar tool), and run this query `SELECT * FROM view_data WHERE is_primary = 1;` what does it say in `account_type`? Do all rows have the same type or are there different ones?

**Comment by aereaux** [comment] 2021-04-12 19:09
The first time I ran that query(with sqlite3), it gave me this, but subsequent runs gave me a result:
```
Error: no such collation sequence: PHONEBOOK
```
But there is only one row returned afterwards, with `account_type` `com.android.contacts`

**Comment by grote** [comment] 2021-04-12 19:15
The PHONEBOOK stuff is expected and unrelated. 

> there is only one row returned afterwards, with account_type com.android.contacts

Does this mean, you have only one single on device contact? If not, drop the `WHERE` close and see what other data is returned. Note that a single contact gets split into several rows.

**Comment by aereaux** [comment] 2021-04-12 19:19
No, I have a lot.  Most of them were recently imported from an export, though.  And I think this is the only one that's been edited since then.  Could that cause this problem?

**Comment by grote** [comment] 2021-04-12 19:21
That shouldn't cause a problem. Maybe all the others are not marked as primary. 

Please try this query `SELECT lookup, data1, account_type FROM view_data;`

**Comment by aereaux** [comment] 2021-04-12 19:23
That query gives me a good number of results, all of which appear to be `com.android.contacts`

**Comment by grote** [comment] 2021-04-12 19:25
Great, thanks a lot! It is really nice having someone report issues that can actually help to debug them.

Let's hope that https://github.com/seedvault-app/seedvault/pull/238 fixes the issue. You might want to ping the LineageOS developers to pick that fix up to receive it earlier.

**Comment by aereaux** [comment] 2021-04-12 19:29
No problem, thanks for the fix.  I'll report it on the lineageos bugtracker.

**Closed** 2021-04-16 18:00 UTC
Labels: bug

**Comment by aereaux** [comment] 2021-04-22 17:47
Thanks for the fix.  Just want to confirm that this has made it into the lineageos build and appears to be working now, although I didn't try restoring.

**Comment by morfikov** [comment] 2021-12-22 07:45
Apparently I also have the same issue, i.e. Waiting to back up in the case of Local contacts.

This query:

`SELECT * FROM view_data WHERE is_primary = 1;`

returns `org.decsync.contacts` as `account_type` .

This query:
`SELECT lookup, data1, account_type FROM view_data;`

Returns many entries with `com.google` , `org.thoughtcrime.securesms` and `org.decsync.contacts`

**Comment by grote** [comment] 2021-12-22 19:53
This is not the same issue, actually it is a non-issue as the backup seems to work as intended. You don't seem to have non-account contacts. The deSync app is responsible for backing up its data via the normal app backup mechanism.

**Comment by morfikov** [comment] 2021-12-26 13:55
I exported the contacts from the google account as .vcf file and imported them to the device. I've also set the the default account for contacts as "Device". When I issue the following command, I get:

```
$ adb shell bmgr backupnow org.calyxos.backup.contacts
Running incremental backup for 1 requested packages.
Package @pm@ with result: Transport error
Backup finished with result: Transport error

```
 So I checked what's in the `/data/data/com.android.providers.contacts/databases/contacts2.db` file:

`$ adb shell "su -c cat /data/data/com.android.providers.contacts/databases/contacts2.db" > contacts2.db`

And when I issue `SELECT * FROM view_data WHERE is_primary = 1;` I get two entries.  The first one is named (account_name) `Personal` and its account_type is `org.decsync.contacts` , which is the previous one. The second entry is named `NULL` and its type is also `NULL` . 

This query `SELECT lookup, data1, account_type FROM view_data;` also returns some additional entries (to the precious ones) but the `account_type` of all of them is set to `NULL`. 

So how to deal with it?

**Comment by grote** [comment] 2022-01-03 19:10
Could you please open a new issue? It shouldn't say `Transport error`. To find out why, we need logcat from the moment you fired the shell backup command.

**Comment by morfikov** [comment] 2022-01-03 19:15
I'll do it in the weekend.

**Comment by morfikov** [comment] 2022-01-08 12:29
It looks like that everything works well when I set `SD card` as a place to store the backup. When I try to backup contacts it works all the time: 

```
$ adb shell bmgr backupnow org.calyxos.backup.contacts
Running incremental backup for 1 requested packages.
Package @pm@ with result: Success
Package org.calyxos.backup.contacts with progress: 512/20480
Package org.calyxos.backup.contacts with progress: 8704/20480
Package org.calyxos.backup.contacts with progress: 16896/20480
Package org.calyxos.backup.contacts with progress: 23552/20480
Package org.calyxos.backup.contacts with res
```

Probably something is wrong with my nextcloud provider. So I think there's no need to create an issue.
