### ISSUE TITLE
seadvault not backing up contacts

### ISSUE THREAD

**Issue by Rihcus** [seedvault-app/seedvault#258] opened 2021-05-26 00:14 UTC
Hi guys using seed vault with nextcloud and noticed contacts will not backup. Apps appdata and everything else does for the most part.

Lineage OS 18.1 OnePlus 8

![Screenshot_20210525-201033_Seedvault](https://user-images.githubusercontent.com/30292597/119583946-aae76400-bd95-11eb-9345-286d0959bb94.png)
![Screenshot_20210525-201134_Settings](https://user-images.githubusercontent.com/30292597/119583953-ad49be00-bd95-11eb-89f6-368ccab7c111.png)

**Comment by Rihcus** [comment] 2021-05-26 00:16
Not sure if this is a lineage os issue or seed vault issue or I'm doing something wrong.

**Comment by chirayudesai** [comment] 2021-05-26 12:46
How old is the build you're running?

This was fixed last month.

**Comment by grote** [comment] 2021-05-26 13:05
potential duplicate of #237

**Closed** 2022-08-22 20:58 UTC
Labels: duplicate
