### ISSUE TITLE
File / Folder browser during Setup Wizard

### ISSUE THREAD

**Issue by FBachofner** [seedvault-app/seedvault#172] opened 2020-12-01 18:59 UTC
When setting up a new device and attempting to restore from USB-OTG, an error message will occur if the .SeedVaultAndroidBackup folder is not in the root of the OTG device.

It would be more user-choice respectful if a file/folder browser were available for the user to indicate where that user has chosen chosen to store the backup folder.

A less good alternative would be to parse through the OTG medium to find all such folders . . . at which point a folder browser is _still_ required to indicate the correct one.

This is important because in some/many cases backups may occur to the "local" Android storage and are then synced to other locations, only then to be put onto OTG media.

Thank you for your consideration.  :-)

**Comment by grote** [comment] 2020-12-01 19:15
Sounds like a duplicate of #143 to me.

I personally consider the current solution much more user-friendly than having the user to provide the correct location or having to search all sorts of folders the right files.

Seedvault saves the backup into the correct location of the backup storage. If you copy it manually to another place, you are responsible for copying it to the correct place.

**Comment by FBachofner** [comment] 2020-12-01 20:53
> Sounds like a duplicate of #143 to me.
> 
> I personally consider the current solution much more user-friendly than having the user to provide the correct location or having to search all sorts of folders the right files.
> 
> Seedvault saves the backup into the correct location of the backup storage. If you copy it manually to another place, you are responsible for copying it to the correct place.

Fair enough.

At that point one of the issues becomes documentation.  I could not find any and therefore stumbled around a bit.

The solution really only occurred to me because I had once sent a SeedVault backup directly to USB_OTG (where it ended up in the root).

Reading #143 it seems like this is all being addressed anyway.

**Continued thanks for your fabulous improvement(s) to the Android ecosystem!**

**Closed** 2020-12-02 00:29 UTC
Labels: duplicate, enhancement
