### ISSUE TITLE
Feature Request: Select backup folder for Nextcloud

### ISSUE THREAD

**Issue by renatobellotti** [seedvault-app/seedvault#205] opened 2021-02-09 17:19 UTC
It would be nice if users could select the directory where the backup will be stored.

Use case:

I have added some HD storage as external storage to my Nextcloud. I would like to use this slow but cheap space instead of the more expensive SSD storage.

**Comment by grote** [comment] 2021-02-09 17:21
Nextcloud is not allowing you to link your HDD or a folder on it to the folder that seedvault uses? If Nextcloud runs on Linux, you could use a symlink.

**Comment by grote** [comment] 2021-02-09 17:22
otherwise, this looks like a duplicate of #143

**Comment by stevesoltys** [comment] 2021-02-17 17:31
Closing since this is a duplicate.

**Closed by stevesoltys** 2021-02-17 17:31 UTC
Labels: duplicate, enhancement
