### ISSUE TITLE
12 word password reset

### ISSUE THREAD

**Issue by polizz** [seedvault-app/seedvault#201] opened 2021-01-21 01:34 UTC
Thank you for a very promising utility.

I'm experiencing something problematic at the moment. When I was first setting up different backup locations, it seemed that I would get new codes every time. However the last time I set it up for nextcloud backup, and it succeeded, it no longer lets me toggle backups off and on in order to generate a final code to record. So I functionally cannot make backups I can use. Is there something I'm missing that I should be doing?

GrapheneOS
Ver: RQ1A.210105.002.2021.01.05.03

**Comment by grote** [comment] 2021-01-21 11:11
> When I was first setting up different backup locations, it seemed that I would get new codes every time. 

Can you reproduce this? It is not the expected behavior. You should be able to change your backup location without a new code.

>  it no longer lets me toggle backups off and on in order to generate a final code to record. 

To clarify: You can turn backup off, but you can't get a new recovery code when doing it? If so, this is the expected behavior.

It seems the "issue" you are reporting is that you want to reset your recovery code, right? If so this is a duplicate of #62.

**Comment by polizz** [comment] 2021-01-21 13:31
Yes, that's correct, I was under the impression that you'd keep getting a new code if you deleted your backups. There is no app to reset from what I can see.

**Comment by grote** [comment] 2021-01-21 13:32
The ability to reset your code has already been merged to master. Also see https://github.com/seedvault-app/seedvault/discussions/190#discussioncomment-272798

**Closed by grote** 2021-01-21 13:32 UTC
