### ISSUE TITLE
Upload over Wi-Fi only

### ISSUE THREAD

**Issue by thereallinusrg** [seedvault-app/seedvault#212] opened 2021-02-23 10:52 UTC
I use Nextcloud as my storag provider. The selection of Nextcloud was very smooth and is nicely integrated.

It would be very helpful, if Seedvault would allow to only do backups when connected to Wi-Fi, as this setting is not globally available in the Nextcloud app. Only for individual folders.

The obvious workaround is to make the backup to a local folder and let the NC app handle the upload.
But that would make the whole process less elegant.

**Comment by grote** [comment] 2021-02-23 11:42
Seedvault writes backups to a DocumentsProvider via SAF and doesn't necessarily know if that will do uploads or not. Also, the backup scheduling is controlled by the system. So somehow attempting to only do backups over WiFi is tricky and can be hacky.

Also, this ticket could be considered a duplicate of #149

**Closed** 2021-02-25 19:33 UTC
Labels: duplicate, enhancement
